### ISSUE TITLE
Misplaced search button in Chrome

### ISSUE THREAD

**Issue by nikhilben** [duckduckgo/chrome-zeroclickinfo#11]
Design breaks while trying to search, the search button is not aligned properly.

![workspace 1_001](https://cloud.githubusercontent.com/assets/355844/5716168/68cc673e-9b0d-11e4-85a6-da5de1864ed2.png)

I am running Chrome Stable (Version 39.0.2171.95)

**Comment by mrshu** [comment]
@nikhilben thanks a ton for this, it's always hard to pinpoint these!

Could you please also tell me which OS were you using when you took this screenshot?

**Comment by nikhilben** [comment]
It's on Ubuntu 12.04LTS 32Bit, but I just confirmed this issue in Windows 7
64-bit running the latest stable Chrome. May be the latest version of
chrome is the problem here ?

**Comment by mrshu** [comment]
Thanks @nikhilben, it seems that the latest Chrome breaks this. It's generally a CSS issue, should not be that difficult to fix.

Thanks for reporting this!

**Comment by mrshu** [comment]
@nikhilben I believe I've fixed this issue in the last built version (https://github.com/duckduckgo/chrome-zeroclickinfo/blob/master/build/chrome-zeroclick-latest.crx?raw=true).


Can you please let me know if that fixes the issue for you? Thanks!

**Comment by nikhilben** [comment]
Yes, the issue is fixed now. Thanks @mrshu
