### ISSUE TITLE
Add the ability to hide the query from the address bar

### ISSUE THREAD

**Issue by nfvs** [duckduckgo/chrome-zeroclickinfo#4]
There should be an option to hide the query from the address bar (if possible at all in Chrome, obviously), as that was the initial reason I installed the extension instead of just using ddg as a chrome search engine.

Apparently the extension is using `chrome.tabs.create()`, which creates a new tab and makes an HTTP GET. I'm not sure if it's possible to make an HTTP POST with the query as parameter instead, but it would be a nice add on.

**Comment by nikhilben** [comment]
hey @mrshu, any update on this ? I think its a good idea to POST rather than GET (So that the ISP's or others cannot log the queries)

But does Duckduckgo support querying through POST ?

**Comment by mrshu** [comment]
hey @nikhilben, not too much, we have prioritized other things. DuckDuckGo does indeed support querying through POST, I believe you can turn this on in the settings.

That being said, I will investigate this further, thanks!

**Comment by nikhilben** [comment]
That's great. Let me try if this can be done :)

**Comment by mrshu** [comment]
Hey @nikhilben, I've added an experimental option to do this. Can you please try it out? 

You can install it from here (https://github.com/duckduckgo/chrome-zeroclickinfo/blob/master/build/chrome-zeroclick-latest.crx?raw=true)

**Comment by nikhilben** [comment]
hey @mrshu, tried out the POST & its working as expected. I think it should be set as enabled by default :)

**Comment by mrshu** [comment]
@nikhilben hah, thanks for trying it out! I think that enabling it by default might seem a bit too confusing for a lot of people.

If @nfvs doesn't have any objections, I will close this in a few days.
